services:
  litellm-laas-server:
    build: .
    container_name: litellm-laas-server
    ports:
      - "${PORT:-4000}:4000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - litellm-network

networks:
  litellm-network:
    driver: bridge

